#!/bin/bash
set -euo pipefail
## This script takes as its input argument the accession of a cultivar from the
## 3K Rice Genome project and produces a VCF file containing all of the called
## sites from that cultivar. It also produces VCF files for each chromosome of
## the cultivar, with indels, Multiple Nucleotide Polymorphisms, and uncalled or
## heterozygous sites removed.


cultivar=$1

root="$(dirname "$(readlink -f "$0")")"
cd $root
source $root/src/environment

# Requires
#module load samtools/1.3 java/1.8.0_40 tabix/0.2.6 bcftools/1.3 vcftools/0.1.13 python/2.7.3

samtools --help
if ["echo $?" != "0"]; then
	module load samtools
	if ["echo $?" != "0"]; then
		echo "could not load samtools module"
fi
bcftools --help
if ["echo $?" != "0"]; then
	module load bcftools
	if ["echo $?" != "0"]; then
		echo "could not load bcftool module"
fi
tabix --help
if ["echo $?" != "1"]; then
	module load tabix
	if ["echo $?" != "1"]; then
		echo "could not load tabix module"
fi
vcftools --help
if ["echo $?" != "0"]; then
	module load vcftools
	if ["echo $?" != "0"]; then
		echo "could not load vcftools"
fi
java -h
if ["echo $?" != "0"]; then
	module load java
	if ["echo$?" != "0"]; then
		echo "could not load java"
fi
python --version
if ["echo $?" != "0"]; then
	module load python/2.7.3
	if ["echo $?" != "0"]; then
		echo "could not load python 2.7.3"
fi

# check reference genome
if [[ ! -e ${reference}/IRGSP-1.0_genome.fasta.fai ]]; then
	echo "You need to run INSTALL script" >&2
	exit 1
fi


# BAM files of sequence read mapping
# Murat figured out how to download these from a site that isn't internet visible.
# https://aws.amazon.com/public-datasets/3000-rice-genome/
cd $maps
wget https://s3.amazonaws.com/3kricegenome/Nipponbare/${cultivar}.realigned.bam
samtools index ${cultivar}.realigned.bam

# The GATK tool Haplotype Caller is used to compare the bam file with the reference genome and generate a gvcf file
cd $calls
call_variants $cultivar

# The GATK tool GenotypeGVCFs takes the gvcf file and produces a normal vcf.
# The option -allSites is necessary for our purposes, so that called sites that match the reference will be able to be compared to SNPs in other cultivars.
full_genotype $cultivar

# Before merging VCFs from different cultivars, it is useful to remove indels and uncalled or heterozygous sites with "bcftools view".
# It is also expedient to split the VCF by chromosome so that merges can be performed with some degree of parallelism.
# This step is not necessary if a merge is not planned.
clean_and_split_vcf $cultivar


