#!/bin/bash
set -euo pipefail

# Create work environment

root="$(dirname "$(readlink -f "$0")")"
cd $root

source $root/src/environment.sh

# Download Picard tool

cd $src
wget "https://github.com/broadinstitute/picard/releases/download/2.10.3/picard.jar"

# Download reference sequence

cd $reference
wget "http://rapdb.dna.affrc.go.jp/download/archive/irgsp1/IRGSP-1.0_genome.fasta.gz"
gunzip IRGSP-1.0_genome.fasta.gz
samtools faidx IRGSP-1.0_genome.fasta
picard CreateSequenceDictionary R=IRGSP-1.0_genome.fasta O=IRGSP-1.0_genome.dict

# Install GATK
cd $src
wget -O GenomeAnalysisTK-3.6-0-g89b7209.tar.bz2 'https://software.broadinstitute.org/gatk/download/auth?package=GATK-archive&version=3.6-0-g89b7209'
tar -xf GenomeAnalysisTK-3.6-0-g89b7209.tar.bz2 && rm GenomeAnalysisTK-3.6-0-g89b7209.tar.bz2
rm -r resources/
echo "Installation Complete"
