#!/bin/bash

#PBS -l nodes=1:ppn=8,walltime=24:00:00,vmem=20gb
#PBS -k o
#PBS -j oe
#PBS -M twmccart@iu.edu
#PBS -m abe

accession=$1

if [[ "$0" =~ "karst" ]]; then
	# load modules for karst
	module load java/1.8.0_40
	root="/N/dc2/scratch/twmccart/VCFs"
else
	root="/DATA/GROUP/twmccart/20cultivarVCFs/"
fi

cd $root

source $root/src/environment.sh

cd $calls

call_variants $accession
