#!/bin/bash

export project_root=$(pwd)
export reference=${project_root}/reference/all.chrs.fix.fasta
export reads=${project_root}/reads
export maps=${project_root}/maps
export calls=${project_root}/calls
export src=$project_root/src
export logs=$project_root/log
export split=${project_root}/split

mkdir -p $reads $maps $calls $logs

export picard="java -jar $src/picard.jar"
export gatk="java -jar $src/GenomeAnalysisTK.jar"

source $src/functions.sh
