#!/bin/bash

export PROJECT_ROOT=$(pwd)
export REFERENCE=${PROJECT_ROOT}/reference/all.chrs.fix.fasta
export READS=${PROJECT_ROOT}/reads
export MAPS=${PROJECT_ROOT}/maps
export CALLS=${PROJECT_ROOT}/calls
export SRC=$PROJECT_ROOT/src
export LOGS=$PROJECT_ROOT/log

mkdir -p $READS $MAPS $CALLS $LOGS

export PICARD="java -jar $SRC/picard.jar"
export GATK="java -jar $SRC/GenomeAnalysisTK.jar"

source $SRC/functions.sh
