#!/bin/bash

#PBS -l nodes=1:ppn=1,walltime=8:00:00,vmem=10gb
#PBS -k o
#PBS -j oe
#PBS -M twmccart@iu.edu
#PBS -m abe

chromosome=$1

if [[ "$0" =~ "karst" ]]; then
	# load modules for karst
	module load bcftools vcftools/0.1.13 tabix
	root="/N/dc2/scratch/twmccart/VCFs"
else
	root="/DATA/GROUP/twmccart/20cultivarVCFs/"
fi

cd $root

source $root/src/environment.sh

cd $split

#for chromosome in {chr01,chr02,chr03,chr04,chr05,chr06,chr07,chr08,chr09,chr10,chr11,chr12}; do
#	merge $chromosome &

merge $chromosome
