#!/bin/bash
#PBS -l nodes=1:ppn=1,walltime=0:20:00,vmem=5gb
#PBS -k o
#PBS -j oe
#PBS -M twmccart@iu.edu
#PBS -m abe

if [[ "$0" =~ "karst" ]]; then
	# load modules for karst
	module load bcftools vcftools/0.1.13 tabix
	root="/N/dc2/scratch/twmccart/VCFs"
else
	root="/DATA/GROUP/twmccart/20cultivarVCFs/"
fi

cd $root

source $root/src/environment.sh

cd $merges

#for file in *.merge.cleaned.vcf; do
#	refilter_merged $file &
#done

file=$1
refilter_merged $file
